apiVersion: v1
kind: PersistentVolume
metadata:
  name: pts-sqlite-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/pts/sqlite-data 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pts-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi